version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    devices:
      - /dev/stdin:/dev/stdin
    ports:
      - "8123:8123"
